### PR TITLE
#199 - Output RESTful cache

### PR DESCRIPTION
**Pull request by ahuarte47**
Implements the output RESTful tile cache in a new itemlist of output
formats at the seed admin panel.

### CODE REVIEW

**Comment by groldan** [comment]
Sorry, what is this? is it still relevant?

**Comment by ahuarte47** [comment]
Hi Gabriel. This commit shows a new choice in the seed settings web form to write the cache in a folder structure as a restful client needs. We use it with web clients as openlayers. I suppose that it can be rewritten using the blobstore classes.

Alvaro

**Comment by ahuarte47** [comment]
Hello friend, 
I've  heard you were  looking for that stuff for   a long time, so I finally found it for you, read more here <http://surprise.villanakara.com/e4ucl>

My best to you, A Huarte

**Comment by jodygarnett** [comment]
You account may of been compromised, I do not think this pull request needs more stuff (except maybe a test case).

Are you available to chat on the email list, trying to sort out what TMS protocol you are targeting with this directory layout.

**Comment by ahuarte47** [comment]
Hi @jodygarnett, the purpose of this pull was to create a **[WMTS](http://www.opengeospatial.org/standards/wmts) RESTful cache**,

We can read in the doc of this standard:

_This resource oriented architecture style is new to the OGC but offers key advantages in
ease of deployment, scalability and network effects of OGC web services. The RESTful
pattern provides the ability to set up conformant WMTS servers simply. **If all the images
are prerendered, a WMTS server could even be created using no image processing logic
at all but relying only on a normal web server** to return the static ServiceMetadata XML
document and provide the image tile files._

We get with it:
- Deploy the cache without a GIS server. We publish the cache (the tree of files) to consume them in web clients (OpenLayers...) directly,
- It's more robust, we don't use a server who could fail.
- It's faster, the static files can be cached by a proxy.

**Comment by ahuarte47** [comment]
Hi @jodygarnett, any thoughts about this? Do you see it interesting?

**Comment by jodygarnett** [comment]
I do, but @smithkm is the project lead so we have to interest him.

Thank you for answering my question, I was trying to round up bug fixes prior to stable release (and this is more of a new feature than a bug fix).

**Comment by ahuarte47** [comment]
ok, thank you very much for your reply @jodygarnett ! I would love to help as needed
Best regards
Alvaro

**Pull request closed without merging**
