### PR TITLE
RexgexParameterFilter.clone returns a non working clone #817

### PR DESCRIPTION
**Pull request by aaime**
@groldan you seem to be the last one to have touched this area of the code, hopefully you remember what was happening. See also https://github.com/GeoWebCache/geowebcache/issues/817

### CODE REVIEW

**Comment by groldan** [comment]
Looks like a simple oversight on 989de950bbf50adcdf9db36cbb5be0668c6d62ee, and that the most appropriate patch would be:
```
diff --git a/geowebcache/core/src/main/java/org/geowebcache/filter/parameters/ParameterFilter.java b/geowebcache/core/src/main/java/org/geowebcache/filter/parameters/ParameterFilter.java
index 4d852d9d..20a30e02 100644
--- a/geowebcache/core/src/main/java/org/geowebcache/filter/parameters/ParameterFilter.java
+++ b/geowebcache/core/src/main/java/org/geowebcache/filter/parameters/ParameterFilter.java
@@ -73,7 +73,13 @@ public abstract class ParameterFilter implements Serializable, Cloneable {
     }
 
     @Override
-    public abstract ParameterFilter clone();
+    public ParameterFilter clone() {
+        try {
+            return (ParameterFilter) super.clone();
+        } catch (CloneNotSupportedException e) {
+            throw new RuntimeException(e);
+        }
+    }
 
     /**
      * Checks whether a given parameter value applies to this filter.
diff --git a/geowebcache/core/src/main/java/org/geowebcache/filter/parameters/RegexParameterFilter.java b/geowebcache/core/src/main/java/org/geowebcache/filter/parameters/RegexParameterFilter.java
index 802c59b2..9dff12a2 100644
--- a/geowebcache/core/src/main/java/org/geowebcache/filter/parameters/RegexParameterFilter.java
+++ b/geowebcache/core/src/main/java/org/geowebcache/filter/parameters/RegexParameterFilter.java
@@ -116,10 +116,7 @@ public class RegexParameterFilter extends CaseNormalizingParameterFilter {
 
     @Override
     public RegexParameterFilter clone() {
-        RegexParameterFilter clone = new RegexParameterFilter();
-        clone.setDefaultValue(getDefaultValue());
-        clone.setKey(getKey());
-        clone.regex = regex;
+        RegexParameterFilter clone = (RegexParameterFilter) super.clone();
         if (super.normalize != null) {
             clone.setNormalize(super.normalize.clone());
         }
diff --git a/geowebcache/core/src/test/java/org/geowebcache/filter/parameters/RegexParameterFilterTest.java b/geowebcache/core/src/test/java/org/geowebcache/filter/parameters/RegexParameterFilterTest.java
index d97ee68f..207c4f17 100644
--- a/geowebcache/core/src/test/java/org/geowebcache/filter/parameters/RegexParameterFilterTest.java
+++ b/geowebcache/core/src/test/java/org/geowebcache/filter/parameters/RegexParameterFilterTest.java
@@ -324,5 +324,8 @@ public class RegexParameterFilterTest {
                 clone.normalize.getConfiguredLocale(),
                 equalTo(filter.normalize.getConfiguredLocale()));
         assertThat(clone.normalize.getCase(), equalTo(filter.normalize.getCase()));
+        // actual regex application test
+        assertTrue(filter.applies("Bar"));
+        assertTrue(clone.applies("Bar"));
     }
 }
```

**Comment by aaime** [comment]
Bizzarre... so there was no reason to implement a custom clone back on 2012?

**Comment by groldan** [comment]
it seems to me there was a reason, to avoid shallow clones, yet the implementation could have depended more in the default clone() functionality and only take care of the special cases like this one

**Comment by aaime** [comment]
Ok, reverted the original change, applied the one you suggested, and extended it to the other ParameterFilter subclasses, does not makes sense to have different cloning behaviors for them, same hierarchy, same module and package...

What do you think? (if you decide to merge, let's use a "squash and merge")

**Comment by groldan** [comment]
yes, looks good to me.

**Pull request merged**
