### PR TITLE
Upgrade Azure Blobstore from legacy azure-sdk (11.0) to latest (12.27.1)

### PR DESCRIPTION
**Pull request by groldan**
## Upgrade `com.microsoft.azure:azure-storage-blob` to `com.azure:azure-storage-blob`.

Add azure storage blob 12.27.1 dependencies and upgrade the  azure blobstore.

Run Azurite-based integration tests against the latest Docker image version, remove legacy.

Migrate to `com.azure:blobstorage:12.x`. The upgrade tries to do a 1:1 migration to the new azure-sdk API (in its blocking falvour) as much as possible, so that the integration tests serve to avoid regressions.

A couple remarks:

* There's no way to close the HTTPClient so AzureClient does not
  implement Closeable anymore.
* Fix a bug in DeleteManager that always reported 0 objects deleted

> This pull request complements https://github.com/geosolutions-it/imageio-ext/pull/312 in the context of GeoServer having compatible transitive dependencies on azure-sdk and their netty dependencies.

### CODE REVIEW

**Comment by groldan** [comment]
Please not the "Azure BlobStore Integration / Azure online" is failing cause my free account expired. I'm waiting for camptocamp to provision an account we can use. Meanwhile, feel free to run `mvn verify -Ponline` against your own account.

**Comment by petersmythe** [comment]
@aaime I understand that you might not be in a position to review this PR.  Is there someone else that you could ask, so that we can get it into GeoServer 2.26.0 by Wednesday (2 days time)?

**Comment by petersmythe** [comment]
> I don't think there is anyone else with familiarity with this module. I'll try to review today.

Thank you, could you let me know if it is approved, please @aaime so that I can continue with GeoTools 32.0 release.

**Comment by aaime** [comment]
I did not manage to review yesterday, too many PRs and I had to do two releases for imageio-ext and jai-ext. Too much ongoing stuff today too... hopefully I'll get to it tomorrow

**Comment by petersmythe** [comment]
@groldan could you please address these 3 comment issues in another PR into main, as I am about to merge this one.

@aaime thank you very much for your time and input.

**Pull request merged**
