### PR TITLE
Update maven repositories

### PR DESCRIPTION
**Pull request by jodygarnett**
Build changes to osgeo repository and use of `https` for maven central.

This is a work-in-progress, as there are no geowebcache changes, other than updated geotools library references, it may not be necessary to make a 1.13.4-1 patch release (to track https://github.com/geotools/geotools/pull/3220 fixes being backported)

### CODE REVIEW

**Comment by jodygarnett** [comment]
Looks like travis is still setup with oracle JDK and is failing due to license. Will have to change to use openjdk ...

**Comment by bradh** [comment]
@jodygarnett Can you re-push this PR (or maybe just close/open)? We are now on github actions, and it needs a rerun.

**Comment by jodygarnett** [comment]
> @jodygarnett Can you re-push this PR (or maybe just close/open)? We are now on github actions, and it needs a rerun.

It may need a rebase to pick up the GitHub actions successfully?

**Comment by bradh** [comment]
Indeed.

**Comment by aaime** [comment]
@jodygarnett so can you rebase it?

**Comment by aaime** [comment]
This PR is stuck, closing, please rebase and re-open in case you want to bring it to merge.

**Comment by jodygarnett** [comment]
Rebasing did not work, no changes on 1.13.x. Trying to reopen to see if that will rerun tests.

**Comment by jodygarnett** [comment]
Build shows that geotools 2.19-SNAPSHOT is no longer available; the PR runs fine for me locally where the jar is available in my local repository. Going to close this and it is here if the customer wants me to resume this activity.

**Pull request closed without merging**
