### PR TITLE
Align FileBlobStore with parameter handling practice of S3/Azure

### PR DESCRIPTION
**Pull request by aaime**
Should address #880

### CODE REVIEW

**Comment by aaime** [comment]
@smithkm updated so that it also removes the old entries from the previous storage (the layer metadata file).
Was easier than I thought, since purgeOrphans ends up calling deleteByParametersId, I just needed to remove the mappings in there.

**Review by groldan — APPROVED** [review]
LGTM

**Comment by aaime** [comment]
@groldan @smithkm how do you feel about a backport of these changes to stable?
https://github.com/GeoWebCache/geowebcache/pull/1230

On one side, it's new, on the other one, the previous approach was not working under load/with many filter parameters.

**Comment by aaime** [comment]
The backport to `1.25.x` failed:
```
The process '/usr/bin/git' failed with exit code 1
```
<details>
<summary>stderr</summary>

```
error: could not apply 48ea5259... Fix javadoc formatting broken by previous commit
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".

```
</details>

<details>
<summary>stdout</summary>

```
[backport-1230-to-1.25.x 7961ddce] Align FileBlobStore with parameter handling practice of S3/Azure
 Author: Andrea Aime <andrea.aime@gmail.com>
 Date: Mon Apr 8 19:42:31 2024 +0200
 2 files changed, 130 insertions(+), 41 deletions(-)
Auto-merging geowebcache/core/src/main/java/org/geowebcache/locks/MemoryLockProvider.java
CONFLICT (content): Merge conflict in geowebcache/core/src/main/java/org/geowebcache/locks/MemoryLockProvider.java

```
</details>

To backport manually, run these commands in your terminal:
```bash
# Fetch latest updates from GitHub
git fetch
# Create a new working tree
git worktree add .worktrees/backport-1.25.x 1.25.x
# Navigate to the new working tree
cd .worktrees/backport-1.25.x
# Create a new branch
git switch --create backport-1230-to-1.25.x
# Cherry-pick the merged commit of this pull request and resolve the conflicts
git cherry-pick c545cf215fb6c080b3b935fb3b5c710223ff4f84,48ea5259e495533d9b7e9b3e93d0fa3d7e4b969d
# Push it to GitHub
git push --set-upstream origin backport-1230-to-1.25.x
# Go back to the original working tree
cd ../..
# Delete the working tree
git worktree remove .worktrees/backport-1.25.x
```
Then, create a pull request where the `base` branch is `1.25.x` and the `compare`/`head` branch is `backport-1230-to-1.25.x`.

**Comment by aaime** [comment]
The backport to `1.24.x` failed:
```
The process '/usr/bin/git' failed with exit code 1
```
<details>
<summary>stderr</summary>

```
error: could not apply 48ea5259... Fix javadoc formatting broken by previous commit
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".

```
</details>

<details>
<summary>stdout</summary>

```
[backport-1230-to-1.24.x f3522275] Align FileBlobStore with parameter handling practice of S3/Azure
 Author: Andrea Aime <andrea.aime@gmail.com>
 Date: Mon Apr 8 19:42:31 2024 +0200
 2 files changed, 130 insertions(+), 41 deletions(-)
Auto-merging geowebcache/core/src/main/java/org/geowebcache/locks/MemoryLockProvider.java
CONFLICT (content): Merge conflict in geowebcache/core/src/main/java/org/geowebcache/locks/MemoryLockProvider.java

```
</details>

To backport manually, run these commands in your terminal:
```bash
# Fetch latest updates from GitHub
git fetch
# Create a new working tree
git worktree add .worktrees/backport-1.24.x 1.24.x
# Navigate to the new working tree
cd .worktrees/backport-1.24.x
# Create a new branch
git switch --create backport-1230-to-1.24.x
# Cherry-pick the merged commit of this pull request and resolve the conflicts
git cherry-pick c545cf215fb6c080b3b935fb3b5c710223ff4f84,48ea5259e495533d9b7e9b3e93d0fa3d7e4b969d
# Push it to GitHub
git push --set-upstream origin backport-1230-to-1.24.x
# Go back to the original working tree
cd ../..
# Delete the working tree
git worktree remove .worktrees/backport-1.24.x
```
Then, create a pull request where the `base` branch is `1.24.x` and the `compare`/`head` branch is `backport-1230-to-1.24.x`.

**Pull request merged**
