### PR TITLE
Update Jackson 2 libs from 2.17.1 to 2.17.2

### PR DESCRIPTION
**Pull request by mprins**
see:
- https://github.com/geoserver/geoserver/pull/7767
- https://github.com/geotools/geotools/pull/4836

### CODE REVIEW

**Comment by aaime** [comment]
Looks like this one was left behind while GT and GS ones were merged. Proceeding to merge and backport, to re-align.

**Comment by aaime** [comment]
The backport to `1.24.x` failed:
```
The process '/usr/bin/git' failed with exit code 1
```
<details>
<summary>stderr</summary>

```
error: could not apply 1d343a87... Update Jackson 2 libs from 2.17.1 to 2.17.2
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
hint: Disable this message with "git config advice.mergeConflict false"

```
</details>

<details>
<summary>stdout</summary>

```
Auto-merging geowebcache/pom.xml
CONFLICT (content): Merge conflict in geowebcache/pom.xml

```
</details>

To backport manually, run these commands in your terminal:
```bash
# Fetch latest updates from GitHub
git fetch
# Create a new working tree
git worktree add .worktrees/backport-1.24.x 1.24.x
# Navigate to the new working tree
cd .worktrees/backport-1.24.x
# Create a new branch
git switch --create backport-1286-to-1.24.x
# Cherry-pick the merged commit of this pull request and resolve the conflicts
git cherry-pick 1d343a870b1fd9447ea6b94fd7ff2698a00c4b4f
# Push it to GitHub
git push --set-upstream origin backport-1286-to-1.24.x
# Go back to the original working tree
cd ../..
# Delete the working tree
git worktree remove .worktrees/backport-1.24.x
```
Then, create a pull request where the `base` branch is `1.24.x` and the `compare`/`head` branch is `backport-1286-to-1.24.x`.

**Comment by mprins** [comment]
> Looks like this one was left behind while GT and GS ones were merged. Proceeding to merge and backport, to re-align.

@aaime I'm, not a member of @GeoWebCache so I can't merge or label anything here

**Comment by aaime** [comment]
Aaah, I see

**Pull request merged**
